name: Build, and Sonar analyze then AST analyze and put results into Sonar

on:
  push:
    branches: [ master ]

jobs:
  Sonar:

    runs-on: ubuntu-latest
    if: ${{ false }}

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.7

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar


      - name: Analyze (sonar)
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=covid-ch_CovidCertificate-Management-Service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
      
  Ast:
    runs-on: ubuntu-latest
    steps: 
     - name: Checkout
       uses: actions/checkout@v2
     - name: Checkmarx AST CLI Action
       uses: Checkmarx/ast-github-action@master
       with:
          project_name: jvlstuff/Cx-Dev-JVL
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.AST_CLIENT_ID }}
          cx_client_secret: ${{ secrets.AST_CLIENT_SECRET }}
          additional_params: --report-format sonar --scan-types sast
     - name: Sonar CLI Action 
       uses: SonarSource/sonarcloud-github-action@master
       env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
       with:
          args: >
            -Dsonar.externalIssuesReportPaths=cx_result_sonar.json
            -Dsonar.projectKey=covid-ch_CovidCertificate-Management-Service
            -Dsonar.organization=covid-ch
            
